// <auto-generated />
using System;
using Kolos2.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos2.Models.BackpackSlots", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<int>("FK_character")
                        .HasColumnType("int")
                        .HasColumnName("FK_character");

                    b.Property<int>("FK_item")
                        .HasColumnType("int")
                        .HasColumnName("FK_item");

                    b.HasKey("PK");

                    b.HasIndex("FK_character");

                    b.HasIndex("FK_item");

                    b.ToTable("Backpack_Slots");

                    b.HasData(
                        new
                        {
                            PK = 1,
                            FK_character = 1,
                            FK_item = 1
                        },
                        new
                        {
                            PK = 2,
                            FK_character = 2,
                            FK_item = 1
                        },
                        new
                        {
                            PK = 3,
                            FK_character = 2,
                            FK_item = 2
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Character", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<int>("CurrentWeig")
                        .HasColumnType("int")
                        .HasColumnName("current_weig");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<int>("Money")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.HasKey("PK");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            PK = 1,
                            CurrentWeig = 10,
                            FirstName = "John",
                            LastName = "Doe",
                            MaxWeight = 13,
                            Money = 1000
                        },
                        new
                        {
                            PK = 2,
                            CurrentWeig = 18,
                            FirstName = "Matt",
                            LastName = "Smith",
                            MaxWeight = 16,
                            Money = 1234
                        },
                        new
                        {
                            PK = 3,
                            CurrentWeig = 0,
                            FirstName = "Will",
                            LastName = "Smith",
                            MaxWeight = 1000000,
                            Money = 1000
                        });
                });

            modelBuilder.Entity("Kolos2.Models.CharactersTitles", b =>
                {
                    b.Property<int>("FKCharact")
                        .HasColumnType("int")
                        .HasColumnName("FK_charact");

                    b.Property<int>("FKTitle")
                        .HasColumnType("int")
                        .HasColumnName("FK_title");

                    b.Property<DateTime>("AquireAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("aquire_at");

                    b.HasKey("FKCharact", "FKTitle");

                    b.HasIndex("FKTitle");

                    b.ToTable("Character_Titles");

                    b.HasData(
                        new
                        {
                            FKCharact = 1,
                            FKTitle = 1,
                            AquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FKCharact = 2,
                            FKTitle = 1,
                            AquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FKCharact = 1,
                            FKTitle = 2,
                            AquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Item", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("weig")
                        .HasColumnType("int")
                        .HasColumnName("weig");

                    b.HasKey("PK");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            PK = 1,
                            name = "item1",
                            weig = 10
                        },
                        new
                        {
                            PK = 2,
                            name = "item2",
                            weig = 12
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Title", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<string>("nam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nam");

                    b.HasKey("PK");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            PK = 1,
                            nam = "name1"
                        },
                        new
                        {
                            PK = 2,
                            nam = "name2"
                        });
                });

            modelBuilder.Entity("Kolos2.Models.BackpackSlots", b =>
                {
                    b.HasOne("Kolos2.Models.Character", "Character")
                        .WithMany("BackpackSlots")
                        .HasForeignKey("FK_character")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("FK_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolos2.Models.CharactersTitles", b =>
                {
                    b.HasOne("Kolos2.Models.Character", "Character")
                        .WithMany("CharactersTitles")
                        .HasForeignKey("FKCharact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.Title", "Title")
                        .WithMany("CharactersTitles")
                        .HasForeignKey("FKTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolos2.Models.Character", b =>
                {
                    b.Navigation("BackpackSlots");

                    b.Navigation("CharactersTitles");
                });

            modelBuilder.Entity("Kolos2.Models.Title", b =>
                {
                    b.Navigation("CharactersTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
